name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/pasang_kaca
            git pull origin main

            # Membuat file .env otomatis
            echo "APP_NAME=${{ secrets.APP_NAME }}" > .env
            echo "APP_ENV=production" >> .env
            echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
            echo "APP_DEBUG=false" >> .env
            echo "APP_URL=${{ secrets.APP_URL }}" >> .env

            echo "DB_CONNECTION=mysql" >> .env
            echo "DB_HOST=mysql" >> .env
            echo "DB_PORT=3306" >> .env
            echo "DB_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
            echo "DB_USERNAME=${{ secrets.MYSQL_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

            # Docker compose rebuild
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
